[package]
name = "busspy"
version = "0.1.7"
description = "BusSpy serial port assistant"
authors = ["BusSpy"]
edition = "2021"

[lib]
name = "busspy_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4"
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
libc = "0.2"
rusqlite = { version = "0.32", features = ["bundled"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls", "gzip"] }
dirs = "5"
rusb = "0.9"
probe-rs = "0.31.0"
